path:
  data_path: '/home/proto/project/BurnSeverity/data'
  out_path: '/home/proto/project/BurnSeverity/result'

params:
  seed : 42
  num_epochs: 200
  batch_size: 8
  learning_rate: 0.0001
  early_stopping_patience : 30
  early_stopping_min_delta : 0.0001